# Generated by Django 4.2.5 on 2023-09-10 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Equipos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clubes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Provincia', models.CharField(max_length=100)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubes', to='App1.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Usuario', models.CharField(max_length=120, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('CrearContraseña', models.CharField(max_length=150)),
                ('Hincha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='App1.clubes')),
            ],
        ),
    ]
